##### Provider -- kubernetesCRD #####
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ingress-route
  namespace: nginx-demo
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: traefik
spec:
  tls:
    secretName: exampledev-tls
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`*`)
      services:
        - kind: Service
          name: nginx-service
          namespace: nginx-demo
          passHostHeader: true
          port: 80
          sticky:
            cookie:
              httpOnly: true
              name: cookie
              sameSite: none
              secure: true