---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blueapp-ingress
  namespace: blue-app
  annotations: 
    kubernetes.io/ingress.class: gce 
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/ingress.global-static-ip-name: "examplelabs-webapps-ip"
spec:  
  rules:
  - host: "blueapp.example.com"
    http:
      paths:
      - pathType: ImplementationSpecific
        path: "/*"
        backend:
          service:
            name: service-blue
            port:
              number: 80